export enum BattleEventType {
  Ambush = "ambush",
  Approach = "approach",
  Crit = "crit",
  Damage = "damage",
  Death = "death",
  Defeat = "defeat",
  Drop = "drop",
  Experience = "experience",
  FleeFailure = "flee-failure",
  FleeSuccess = "flee-success",
  FriendlyTargetFailure = "friendly-target-failure",
  GainStat = "gain-stat",
  Gold = "gold",
  Heal = "heal",
  Instakill = "instakill",
  InstakillFinish = "instakill-finish",
  InventoryFull = "inventory-full",
  LevelUp = "level-up",
  Miss = "miss",
  NewLevel = "new-level",
  Obtain = "obtain",
  Rejuvenate = "rejuvenate",
  UseAbility = "use-ability",
  UseItem = "use-item",
}
