export enum BattleEventType {
  Approach = "approach",
  Crit = "crit",
  Damage = "damage",
  Death = "death",
  Defeat = "defeat",
  Experience = "experience",
  FriendlyTargetFailure = "friendly-target-failure",
  GainStat = "gain-stat",
  Gold = "gold",
  Heal = "heal",
  Instakill = "instakill",
  LevelUp = "level-up",
  Miss = "miss",
  NewLevel = "new-level",
  Rejuvenate = "rejuvenate",
  UseAbility = "use-ability",
  UseItem = "use-item",
}
