export enum ChatType {
  Ban = "ban",
  IPBan = "ip-ban",
  Kick = "kick",
  Login = "login",
  Logout = "logout",
  Message = "message",
  Mute = "mute",
  PartyJoin = "party-join",
  PartyLeave = "party-leave",
  Rename = "rename",
  Unban = "unban",
  Unmute = "unmute",
  Warn = "warn",
}
